version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ascopes"
    # labels:
    #  - "maven"
    #  - "housekeeping"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ascopes"
    # labels:
    #  - "maven"
    #  - "housekeeping"
