name: Build
on:
  pull_request:
    branches: [ "**" ]
    types: [ opened, synchronize ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # Enables adding a comment to PRs with test results.
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Needed to keep actions working correctly.
          fetch-depth: 2

      - name: Initialize JDK
        uses: actions/setup-java@v4
        with:
          cache: maven
          check-latest: true
          distribution: zulu
          java-version: 17

      - name: Compile and run tests
        shell: bash
        run: ./mvnw -B clean verify

      - name: Archive Surefire and Jacoco reports
        uses: actions/upload-artifact@4
        if: always()
        with:
          name: reports
          path: |
            **/target/*-reports/*.xml
            **/target/*-reports/*.txt
          retention-days: 5

      - name: Publish to codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        if: always()
        
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        continue-on-error: true
        with:
          junit_files: "**/target/*-reports/TEST-*.xml"
