name: Build
on:
  pull_request:
    branches: [ "**" ]
    types: [ opened, synchronize ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # Enables adding a comment to PRs with test results.
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0
        with:
          # Needed to keep actions working correctly.
          fetch-depth: 2

      - name: Initialize JDK
        uses: actions/setup-java@v3.12.0
        with:
          cache: maven
          check-latest: true
          distribution: zulu
          java-version: 17

      - name: Compile and run tests
        shell: bash
        run: ./mvnw -B -e -U --no-transfer-progress -Dstyle.color=always clean verify

      - name: Archive Surefire and Jacoco reports
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: reports
          path: |
            **/target/*-reports/*.xml
            **/target/*-reports/*.txt
            **/target/site/jacoco/jacoco*.xml
          retention-days: 5

      - name: Publish to codecov
        continue-on-error: true
        if: always()
        shell: bash
        run: |-
          curl --fail https://keybase.io/codecovsecurity/pgp_keys.asc \
              | gpg --no-default-keyring --keyring trustedkeys.gpg --import
          curl --fail -Os https://uploader.codecov.io/latest/linux/codecov
          curl --fail -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
          curl --fail -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
          gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
          shasum -a 256 -c codecov.SHA256SUM
          chmod -v +x codecov
          ./codecov 

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: always()
        continue-on-error: true
        with:
          junit_files: "**/target/*-reports/TEST-*.xml"
